In [1]:
import numpy as np

In [2]:
# Create array using numpy
# 1D Array:
arr1 = np.array([1,2,3,4,5])

In [6]:
print(arr1, type(arr1))
print(arr1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)


Create a new 1D array and reshape it to 2D array

In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

.reshape: To re-shape ndarray.
1. In above example arr2 is 1D array.
2. Reshaped array is viewd as having 2 open/close brackets - which signifies that it is a 2D array.
3. Reshaped it to (1,5) -> (row,col)

In [15]:
#Creating 2D Array
arr3 = np.array([[1, 2, 3, 4, 5]])
arr3.shape #(1,5) signifies it has 1 row & 5 col

(1, 5)

In [13]:
arr4 = np.array([[1, 2, 3, 4, 5],[2, 3, 4, 5, 6]])
print(arr4, arr4.shape, type(arr4), sep="\n")

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
<class 'numpy.ndarray'>


In [16]:
!git config --global user.email "chitleysamarth@gmail.com"
!git config --global user.name "samarth-chitley"